#!/bin/bash

usage()
{
  echo "Usage: $0 [ -k SHIFT ] [-u]" 
  exit 2
}

kset=0
karg=0
uset=0
uarg=0

while getopts "k:u" option; do
  case $option in
    (k) kset=1
        karg=$OPTARG;;
    (u) uset=1
        ;;
  esac
done

n=$((25-$karg))

array1=(a b c d e f g h i j k l m n o p q r s t u v w x y z)

for (( i = 0; i <= n; i++ ))
do
 p=$(($i+$karg))
 array2[$i]=${array1[$p]}
 echo "array2[i] p1= "${array2[$i]}" i = "$i
done

for (( i=n+1; i<=25; i++ ))
do
 p=$(($i-$n-1))
 array2[$i]=${array1[$p]}
 echo "array2[i] p2= "${array2[$i]}" i = "$i
done

os="["${array2[0]}"-"${array2[$n]}${array2[$(($n+1))]}"-"${array2[25]}"]"
pps=$os

if (( uset==1 ))
then
    echo $pps | tr '[a-z]' '[A-Z]'
else
    echo $pps
fi