#!/bin/bash

## Initialising variables
cipherShift=0
uppercase=0

## getops for the cipherShift (-k $OPTARG) and uppercase (-u)
while getopts "k:u" option; do
  case $option in
    (k) cipherShift=$OPTARG;;
    (u) uppercase=1;;
  esac
done

alphabetArray=(a b c d e f g h i j k l m n o p q r s t u v w x y z) # it's the alphabet in standard order all lowercase...

## formatting the pattern for output
pattern="["${alphabetArray[$cipherShift]}"-za-"${alphabetArray[$(($cipherShift-1))]}"]"

if (( uppercase == 1 )) # checks if uppercase (the -u argument) was triggered
then
  echo $pattern | tr '[a-z]' '[A-Z]'; # translates [pattern to uppercase]
else
  echo $pattern;
fi