#!/bin/bash

usage()
{
  echo "Usage: $0 [ -k SHIFT ] [-u]" 
  exit 2
}

## Initialising variables
cipherShift=0
uppercase=0


## getops for the cipherShift (-k $OPTARG) and uppercase (-u)
while getopts "k:u" option; do
  case $option in
    (k) cipherShift=$OPTARG;;
    (u) uppercase=1;;
  esac
done

echo "a"

newPattern = exec ./create_pattern

if (( uppercase == 1 ))
then
  #trPattern = echo $(exec ./create_pattern -k $cipherShift -u)
  while read line;
  do 
     echo ${line} | tr '[a-z]' '[A-Z]' | tr '[A-Z]' 
  done < a_file_full_of_text;

else
  trPattern = exec ./create_pattern -k $cipherShift
fi

echo "b"

echo $trPattern

