#!/bin/bash

## Initialising variables
cipherShift=0
uppercase=0

## getops for the cipherShift (-k $OPTARG) and uppercase (-u)
while getopts "k:u" option; do
  case $option in
    (k) cipherShift=$OPTARG;;
    (u) uppercase=1;;
  esac
done

if (( uppercase == 1 ))
then
  #trPattern = echo $(exec ./create_pattern -k $cipherShift -u)
  while read line;
  do 
     echo ${line} | tr '[a-z]' '[A-Z]' | tr '[A-Z]' $(./create_pattern -k $cipherShift -u)
  done < a_file_full_of_text;

else
  #trPattern = echo $(exec ./create_pattern -k $cipherShift -u)
  while read line;
  do 
     echo ${line} | tr '[A-Z]' '[a-z]' | tr '[a-z]' $(./create_pattern -k $cipherShift)
  done < a_file_full_of_text;
fi