#!/bin/bash

## Initialising variables
cipherShift=0
uppercase=0

## getops for the cipherShift (-k $OPTARG) and uppercase (-u)
while getopts "k:u" option; do
  case $option in
    (k) cipherShift=$OPTARG;;
    (u) uppercase=1;;
  esac
done

if (( uppercase == 1 ))
then
  while read line;
  do 
    #prints line   #tr from lower to cap  #tr from cap to the new pattern
     echo ${line} | tr '[a-z]' '[A-Z]' | tr '[A-Z]' $(./create_pattern -k $cipherShift -u)
  done < a_file_full_of_text;

else
  while read line;
  do 
    #prints line   #tr from cap to lower  #tr from cap to the new pattern
     echo ${line} | tr '[A-Z]' '[a-z]' | tr '[a-z]' $(./create_pattern -k $cipherShift)
  done < a_file_full_of_text;
fi